### ISSUE TITLE
Use btcdrak's addrindex branch instead of jmcorgan's

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/federatednode_build#178]
This is jmcorgan's patch, but applied to Bitcoin Core 0.10.

The patch: https://github.com/btcdrak/bitcoin/compare/bitcoin:0.10...addrindex

Viacoin's uses Bitcoin Core codebase 0.10 + this addrindex patch so it's been tested for some months.

**Comment by rippler** [comment]
I've been running `counterpartyd` 9.49 with that code on Lin and Win, no problems so far.

Those who want to kick tires in a test environment can try my unofficial binaries (on Linux it's trivial to build them but on Windows it's a hassle).
https://github.com/rippler/bitcoin-core-0.10.0-addrindex

**Comment by btcdrak** [comment]
@adamkrellenstein I'll compile binaries using gitian builder (the official way which is deterministic and therefore verifiable) if you like.

**Comment by adamkrellenstein** [comment]
@robby-dermody, @ouziel-slama, binaries?

**Comment by btcdrak** [comment]
It's like no stress to do, I have gitian VM setup, it just takes 30 mins or whatever to run.

**Comment by robby-dermody** [comment]
For windows absolutely... For Linux, either way can work. We're compiling from source in the setup today.

If people have concerns of what they are running, it may make sense to stay with local source compilation (when using the scripts). With windows, it's just a pragmatic decision, since it's so involved to compile bcd on there...

**Comment by btcdrak** [comment]
Here you go: https://github.com/btcdrak/bitcoin/releases/tag/addrindex-0.10.0

These are deterministically built using the same build process used by the Bitcoin devs for the official client.

**Comment by mtbitcoin** [comment]
+1 Binaries for windows from a 'trusted' source is a must.

**Comment by robby-dermody** [comment]
@btcdrak looks good. I'd still like to do/see a cross repo diff to see exactly how this differs from the parent before we factor this in. (guess we could do something like: http://stackoverflow.com/questions/3792989/how-to-view-diff-of-a-forked-github-project)

Everyone else in favor of going with this build?

**Comment by adamkrellenstein** [comment]
@robby-dermody, the difference between this repo and Bitcoin Core 0.10 is here:  btcdrak/bitcoin@bitcoin:0.10...addrindex

**Comment by adamkrellenstein** [comment]
Recommending this version in the counterpartyd README: 39d33b17a3a7d6558eb56af42afdbf8d87aff9be

**Comment by btcdrak** [comment]
When Bitcoin Core 0.10.0 final is released I make another tag and build.

**Comment by robby-dermody** [comment]
implemented. closing
