### ISSUE TITLE
Edge scenario with then without counterblockd

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#179]
I'm running the current develop branches (`counterpartyd_build` and `counterpartyd`). I've done a bunch of reinstalls today si I'm not 100% sure what happened but I  think I had `counterpartyd` installed `--with-counterblockd` and then - in course of trying out those fixes from today - I wiped `counterpartyd_build` (`master`) and re-installed stand-alone `counterpartyd` from `develop`. 
Now `counterpartyd-testnet` can't start. It looks like the previous `counterblockd` may be causing some troubles here, although I can't tell for sure.
Restarting counterpartyd didn't help. This process always remains and when `kill`-ed` it automatically comes back. I did not reboot the machine since I upgraded to `develop`. It may be that it's running from before.

```
root       774     1  0 Jan02 ?        00:00:02 runsvdir -P /etc/service log: ........................................\
...............[INFO] Running v9.49.3 of counterpartyd.?[0m [INFO] Connecting to backend.?[0m [INFO]\
 Acquiring lock.?[0m [INFO] Connecting to database.?[0m [INFO] Connecting to block explorer.?[0m \
[INFO] Resuming parsing.?[0m ......\
```
and
```
root     27492     1  0 12:17 ?        00:00:00 runsvdir -P /etc/service log: failure runsv counterpartyd-\
testnet: fatal: unable to lock supervise/lock: temporary failure runsv mongod: fatal: unable to lock \
supervise/lock: temporary failure runsv counterpartyd: fatal: unable to lock supervise/lock: temporary \
failure runsv counterpartyd-testnet: fatal: unable to lock supervise/lock: temporary failure runsv \
mongod: fatal: unable to lock supervise/lock: temporary failure \
```
I rebooted and now `counterpartyd` can start. Is there a way to remove leftovers of previous `--with-counterblockd` without rebooting the OS?

**Comment by robby-dermody** [comment]
I don't think so...

**Comment by robby-dermody** [comment]
you could try stopping counterblockd and counterblockd-testnet (and mongodb) before you blow everything away ;)

**Comment by robby-dermody** [comment]
closing. reopen if still an issue
