### ISSUE TITLE
Translation files not downloaded

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#183]
Had to manually execute this:
```
sudo su -s /bin/bash -c 'grunt transifex --force' xcp
```

**Comment by robby-dermody** [comment]
We don't auto download them because transifex requires a username and password to do so (and I'd rather not hardcode one in the script).

```
Warning: You must put a transifex user and password in /home/xcp/.transifex in this format: user:password
 Used --force, continuing.
```

Can you enhance the fednode doc (near the end) to note this, and provide instructions as to what the user should do to grab them?

**Comment by robby-dermody** [comment]
fixed here https://github.com/CounterpartyXCP/Documentation/commit/565ff80b77fc1c4ac300717f58c79d0ddb32c1b2
