### ISSUE TITLE
Consider adding 3rd party packages "advice" to the update routine

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#185]
Since 3rd party packages (Armory, Bitcoin Core, etc.) come externally, they can't get automatically updated.

I think it would be enough to query whether what's installed is older than what setup script would install were it to rebuild Fed Node and throw a warning that those are outdated.

**Comment by rippler** [comment]
I tried to get Bitcoin Core Addrindex 0.10.0 by running `(U)pdate` on Federated Node 1.1.0.
It didn't touch bitcoin-core, so I updated it manually. Within Fed Node build system currently the only way is to `(r)ebuild`. 
This is just to update this with the current Fed Node 1.1.0 status.

**Comment by robby-dermody** [comment]
That is by design. Update shouldn't update bitcoin core... Only counterparty-related things

**Comment by rippler** [comment]
Fair enough. Closing this
