### ISSUE TITLE
Fed Node 9.49.3->Develop: counterpartyd can't run after Rebuild

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#192]
Rebuilt using `develop` `counterpartyd_build` scripts to simulate the upgrade from 9.49.3. 
It all worked well, except that `counterpartyd` can't start and judging by the log it hasn't started ever since I shut it down as v9.49.3:

```
rippler@ubuntu:~$ sudo su -s /bin/bash -c 'counterpartyd -V' xcpd
/home/xcp/counterpartyd_build/env/bin/python: can't open file '/home/xcp/counterpartyd_build/dist/counterpartyd/counterpartyd.py': [Errno 2] No such file or directory
rippler@ubuntu:~$ sudo dir -la /home/xcp/.config/counterpartyd/counterpartyd.log
-rw-rw-r-- 1 xcpd xcp 9371842 Jan 22 17:37 /home/xcp/.config/counterpartyd/counterpartyd.log
rippler@ubuntu:~$ date
Fri Jan 23 03:05:23 UTC 2015
rippler@ubuntu:~$ ll /home/xcp/counterpartyd_build/dist/counterpartyd/counterpartyd.py
ls: cannot access /home/xcp/counterpartyd_build/dist/counterpartyd/counterpartyd.py: No such file or directory
```

**Comment by robby-dermody** [comment]
The newest version removed the counterpartyd.py file. Run.py will probably go away or change a lot at the least... If you got to this point, we should be good

**Comment by robby-dermody** [comment]
is this still an issue?

**Comment by rippler** [comment]
I didn't notice it in recent days (and I did try to upgrade from 9.49.3), so I think it's been fixed.
