### ISSUE TITLE
1.1.1 dev: CW config not installed

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#212]
I think I installed CW. 
```
2015-02-10-T10:37:43+0000:WARNING:startup:Counterwallet config does not exist at '/home/xcp/counterwallet/counterwallet.conf.json'. Counterwallet functionality disabled...
```
The doc says nothing about this extra step:
> You will then be presented to accept your self-signed SSL certificate, and after doing that, should see the web interface for the role you selected (e.g. Counterwallet login screen, if Counterwallet was chosen at node setup time). From this point, you can proceed testing the necessary functionality on your own system(s)

Either the sample config should be copied to the right place or the doc could be fixed to remind of this step.

**Comment by robby-dermody** [comment]
fed node doc updated to clarify this. check my recent commits to the documentation repo
