### ISSUE TITLE
1.1.1 dev: location of bitcoin testnet config file

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#213]
Upgrade from 9.49.3 to 9.49.4 via FNB 1.1.1 develop: spent 30 mins trying to figure out why counterparty server couldn't connect... 
Turns out, I was troubleshooting a wrong file:

Before:
https://github.com/CounterpartyXCP/federatednode_build/blob/b6f97c35ee60e34c1c9ce724f1ebb95cc160dbf2/setup_federated_node.py#L127: `bitcoin-testnet/bitcoin.conf`

Now:
https://github.com/CounterpartyXCP/federatednode_build/blob/4e43d8fc7a45de1c248005875dfc88f07bbad77f/run.py#L301: `.bitcoin/bitcoin.testnet.conf`

It may be that the old file used to be symlinked to the current location, but I can't see that in the code.

**Comment by robby-dermody** [comment]
Yeah, ill get the release tagged today with the release notes, that note this change... The updated docs should also note this config file change as well

**Comment by robby-dermody** [comment]
It's a new location for that file, actually. The setup script should probably rename that file to .old or something to make that more clear (or rename it over and go off of that for starters, instead of making a new file from scratch)

**Comment by robby-dermody** [comment]
release notes will clarify this change
