### ISSUE TITLE
rpc-user missing in server.conf, counterparty-password employed by counterblock config

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#215]
* Counterparty server seems to be missing `rpc-user` (both testnet and mainnet config files)
* Counterblock server too 
* `counterparty-password` is employed by counterblock config files: https://github.com/CounterpartyXCP/federatednode_build/blob/develop/run.py#L395

**Comment by robby-dermody** [comment]
* rpc-user was removed as we use the default value for it, and explicitly specifying it is unnecessary now
* what's the issue with `counterparty-password`? it's a valid configuration value

all of this seems normal, is it causing issues?

**Comment by rippler** [comment]
* I reported it as a matter of consistency because `server.conf` on my counterparty-lib instances does contain that field (or at least did until a few days ago). Inconsistency makes it more difficult to troubleshoot (when one sees the option here, and then it's missing there).
* I didn't know about `counterparty-password` being valid in counterblock. It used to be valid in `server.conf`, but I expected that (since `rpc-user` is the user option) `rpc-password` would be the option for the password setting across different projects. 
Here's what I get from `counterparty-server --help` (`counterparty-lib` v1.0.0):
```
  --rpc-host RPC_HOST   the IP of the interface to bind to for providing JSON-
                        RPC API access (0.0.0.0 for all interfaces)
  --rpc-port RPC_PORT   port on which to provide the counterparty JSON-RPC API
  --rpc-user RPC_USER   required username to use the counterparty JSON-RPC API
                        (via HTTP basic auth)
  --rpc-password RPC_PASSWORD
                        required password (for rpc-user) to use the
                        counterparty JSON-RPC API (via HTTP basic auth)
```
If it's how it's supposed to be, then I'll close this. It could be less confusing, though.
