### ISSUE TITLE
Fed Node 1.1.0 sets wrong bitcoin RPC password in server.conf

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#222]
... and a non-random password for server itself. Testnet conf is fine.
```
rippler@ubuntu:~$ sudo cat /home/xcp/.bitcoin/bitcoin.conf
rpcuser=rpc
rpcpassword=enc9Rdu0dgE2cr
server=1
daemon=1
rpcthreads=1000
rpctimeout=300
txindex=1
addrindex=1

rippler@ubuntu:~$ sudo cat /home/xcp/.config/counterparty/server.conf
[Default]
backend-user=rpc
backend-password=1234
rpc-password=xcppw1234

rippler@ubuntu:~$ sudo cat /home/xcp/.config/counterblock/server.conf
[Default]
backend-user=rpc
backend-password=1234
counterparty-password=xcppw1234
rpc-host=0.0.0.0
socketio-host=0.0.0.0
socketio-chat-host=0.0.0.0
redis-enable-apicache=0
armory-utxsvr-enable=1
```

**Comment by robby-dermody** [comment]
hmm, I can't see how that's possible from the code. can you try removing the counterparty and counterblock server.conf files and trying again? also, which option did you choose, "counterpartyd only", with 'y' to the public interface option??

**Comment by rippler** [comment]
I got this duplicated more than once:
- Rebuild
- Counterwallet
- Master
- Both
- no email
- No hardening
- No autostartup

**Comment by rippler** [comment]
You're right, it's not appearing in clean install. Weird.
