### ISSUE TITLE
Should update redownload databases?

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/federatednode_build#224]
Related to https://github.com/CounterpartyXCP/federatednode_build/issues/223, I noticed that CP databases are downloaded even though I already have them and I only chose `(U)pdate`, which in my mind should only update counterparty-lib, counterblockd, and such. 

I ran `(U)pdate` on Fed Node 1.1.0 (which I installed yesterday) and since nothing changed in terms of code, Counterparty databases probably should not be downloaded again.

**Comment by robby-dermody** [comment]
Most likely a bug. Did you delete the dist/counterpartylib dir/symlink before running that? That would cause that behavior:

    do_bootstrap = not os.path.exists(COUNTERPARTY_LIB_DIST_PATH)

(Sorry on mobile)

**Comment by robby-dermody** [comment]
I'll change that check to be more accurate... Was going to do that anyhow

**Comment by rippler** [comment]
I didn't do anything to prepare for that, I just stopped services, downloaded the latest `run.py` and run with with `(U)pdate`.
