### ISSUE TITLE
Remove rpcthreads from bitcoin.conf?

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode_build#265]
In here: 
https://github.com/CounterpartyXCP/federatednode_build/blob/master/run.py#L302

1,000 threads is a lot. I've been running with 4. 
I'm not convinced the setting helps, but I've no way to prove it.  If 4 is enough, we're potentially consuming too much resources or making things slower. I don't know how we could check if a lower value makes sense.

Secondly `\nminrelaytxfee=0.00005\nlimitfreerelay=0` in the same line can probably be removed because v0.12 takes care of spam in a flexible manner.

From https://bitcoin.org/en/release/v0.12.0

> Previous versions of Bitcoin Core had their mempool limited by checking a transaction’s fees against the node’s minimum relay fee. There was no upper bound on the size of the mempool and attackers could send a large number of transactions paying just slighly more than the default minimum relay fee to crash nodes with relatively low RAM. A temporary workaround for previous versions of Bitcoin Core was to raise the default minimum relay fee.

> Bitcoin Core 0.12 will have a strict maximum size on the mempool. The default value is 300 MB and can be configured with the -maxmempool parameter. Whenever a transaction would cause the mempool to exceed its maximum size, the transaction that (along with in-mempool descendants) has the lowest total feerate (as a package) will be evicted and the node’s effective minimum relay feerate will be increased to match this feerate plus the initial minimum relay feerate. The initial minimum relay feerate is set to 1000 satoshis per kB.

**Comment by robby-dermody** [comment]
I'm suspecting the same thing, especially that were doing a better job batching transactions now with the updated RPC backend code over the past few releases. I'll try running cw01 with 100 threads for starters and see how that performs.

Regarding the mempool, I'm curious to what counterparty-server's memory footprint may be when the bitcoind mempool hits that 300mb default max.

With the armory utxsvr fix and armory upgrade I made last night, federated nodes should be able to run 0.12 no problem, end to end (and indeed, the setup script has been updated to bitcoind 0.12). But how this mempool improvement impacts a running counterparty server on a variety of memory configurations is still not fully clear and will need some runtime to become fully fleshed out.
