### ISSUE TITLE
Investigation of Ubuntu 16.04 x86_64

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/federatednode_build#269]
* PYTHON3_VER = "3.5" should be used with Ubuntu 16.04 
* libzmq3 is not available in this version and it probably can be removed from run.py (libzmq3-dev is still available); libzmq5 could probably be used instead
* ruby1.9.1 and ruby1.9.1-dev in run.py should be replaced with ruby2.3, ruby2.3-dev (in the OpenResty section)
* NodeJS can now be installed using apt-get (no need to use custom repo, in fact the custom repo fails to work with 16.04); Ubuntu 16.04 ships with NodeJS 4.2.6

With these changes (plus a fix for the changed Armory download link that I just submitted) Federated Node Build installs fine. I haven't tested the components, I just made sure install can finish and bitcoin and counterparty-server can start.

**Comment by robby-dermody** [comment]
+1 as this is the new LTS release, but I think we will need to support both 14.04 and 16.04 for some time. (making the build script work with either)... thoughts?

**Comment by unsystemizer** [comment]
That's my hope. If OS version detected is 16.04 we can just do 3-4 things differently and run.py can complete regardless of which LTS version is used. (By the way, I changed 14.04 to 16.04 in https://github.com/CounterpartyXCP/federatednode_build/blob/master/run.py#L162 to make run.py not stop).

**Comment by unsystemizer** [comment]
An attempt to make required changes: https://github.com/CounterpartyXCP/federatednode_build/pull/270
